### ISSUE TITLE
question

### ISSUE THREAD

**Issue by wjczf123** [moore3930/SlotRefine#1]
It's a nice work to use non-autoregressive model to solve joint intent detection and slot filling problem.
I have a problem about two-pass refine mechanism. As you say in Figure1:
In the first pass, wrong slot tagging results are predicted, as shown in the pink dotted box in the figure, and the “B-tags” (beginning tag of a slot) are feeded as additional information with utterance for second iteration.

I am very curious about the effect if the prediction results of the first pass are directly used as input to the second pass (i.e., not only B-tags. We copy the result of the first pass).

Finally I am looking forward to your code. Thank you!

**Comment by moore3930** [comment]
We haven't try the method you mentioned above. Intuitively, such approach is quite similar to MaskPredict, except that there is no probabilistic choice for the tagging results. Certainly, methods similar to MaskPredict can also alleviate the problem of conditional independence. However, it’s designed for a more complex goal, and it usually introduce more iterations (e.g., 10 iters in MT) to achieve competitive performance, which also reduces the inference speed.

The code will come soon. Thanks for your attention.

**Comment by wjczf123** [comment]
OK. Thank you a lot.

**Comment by moore3930** [comment]
Hi,

The code has been released. If you have any questions, please feel free to contact us.

Thanks for your attention to SlotRefine.

Best Regards.

Di Wu

**Comment by moore3930** [comment]
Hi All,

The code has been released. If you have any questions, please feel free to contact us.

Thanks for your attention to SlotRefine.

Best Regards.

Di Wu
